version: '3'

services:

  flask:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - redis

  rq-worker:
    build: ./app
    command: rq worker -u redis://redis:6379 --worker-ttl -1 --results-ttl -1
    depends_on:
      - redis

  redis:
    image: redis