version: '3'

services:

  flask:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - /app
    depends_on:
      - redis

  rq-worker:
    build: ./app
    command: rq worker -u redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis