version: '3.6'

services:

  flask:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - redis

  rq-worker:
    build: ./app/worker
    command: rq worker -u redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis